### ISSUE TITLE
[1.10.2] Console Error spam

### ISSUE THREAD

**Issue by DaNeo61** [Matryoshika/Underworld#10]
Mod: underworld-1.10.2-0.1.12a.jar

Currently getting only errors Spams

> [17:07:53] [Server thread/INFO] [STDERR/]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:111]: java.lang.reflect.InvocationTargetException
[17:07:53] [Server thread/INFO] [STDERR/]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:111]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[17:07:53] [Server thread/INFO] [STDERR/]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:111]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[17:07:53] [Server thread/INFO] [STDERR/]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:111]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[17:07:53] [Server thread/INFO] [STDERR/]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:111]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[17:07:53] [Server thread/INFO] [STDERR/]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:111]: 	at se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner.doSpawn(TileInvisMobSpawner.java:95)
[17:07:53] [Server thread/INFO] [STDERR/]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:111]: 	at se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner.func_73660_a(TileInvisMobSpawner.java:58)
[17:07:53] [Server thread/INFO] [STDERR/]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:111]: 	at net.minecraft.world.World.func_72939_s(World.java:1804)
[17:07:53] [Server thread/INFO] [STDERR/]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:111]: 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
[17:07:53] [Server thread/INFO] [STDERR/]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:111]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
[17:07:53] [Server thread/INFO] [STDERR/]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:111]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
[17:07:53] [Server thread/INFO] [STDERR/]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:111]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
[17:07:53] [Server thread/INFO] [STDERR/]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:111]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
[17:07:53] [Server thread/INFO] [STDERR/]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:111]: 	at java.lang.Thread.run(Thread.java:745)
[17:07:53] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.NoSuchMethodError: elucent.roots.entity.EntityFrostShard.func_70016_h(DDD)V
[17:07:53] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:634]: 	at elucent.roots.entity.EntityFrostShard.<init>(EntityFrostShard.java:63)
[17:07:53] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:634]: 	... 13 more

**Comment by Matryoshika** [comment]
> Caused by: java.lang.NoSuchMethodError:
[Line that is causing it](https://github.com/Matryoshika/Underworld/blob/master/src/main/java/se/Matryoshika/Underworld/Content/TileEntity/TileInvisMobSpawner.java#L111).
What? This was supposed to have been fixed back in update 0.0.9 >_>
You sure that you are using 0.1.12?
Line 111 can only print SecurityExceptions, InstantiationException, IllegalAccessException, IllegalArgumentException & InvocationTargetException. 
NoSuchMethodExceptions are handled on **113** and they are _ignored_... Something doesn't add up right

**Comment by DaNeo61** [comment]
@Matryoshika i updated forge and the error was gone sorry that i missed to say you that

**Comment by Matryoshika** [comment]
To import my repository into any IDE, you will need to first setup a [Forge environment](http://www.minecraftforge.net/forum/index.php?topic=14048.0) :) This _is_ a Minecraft mod using the Forge-API

I'm still wondering if you are using build 0.1.12. As said, this should have been fixed way back in 0.0.9.
I have likely fixed this issue, but in case it doesn't work, I also added a "gate" to only post an exception once every max 20 seconds. Should lessen spam considerably.

**Comment by DaNeo61** [comment]
> To import my repository into any IDE, you will need to first setup a Forge environment :) This is a Minecraft mod using the Forge-API

I know that it is a Forge Mod i have everthing on my pc.

It says following 
<script src="https://gist.github.com/DaNeo61/176342fb65b79ed35c016e5e2e90d7d2.js"></script>

**Comment by DaNeo61** [comment]
Forge MDK 1.10.2-12.18.3.2185
and i just added as libary:
jei_1.10.2-3.13.6.387.jar by mezz
