### ISSUE TITLE
Crash Issue on Server

### ISSUE THREAD

**Issue by leezallen** [Matryoshika/Underworld#16]
Hi, 

Having a crash issue with the latest version when starting on a server as follows. Sorry for the long crash report! Can seem to find the spoiler tags in GitHub!

(Still loving the mod by the way! The first modpack proved quite popular so now designing a second one around it with all the recommendations that we have for changes!)

Lee

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 19/01/17 11:27
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Underworld (underworld)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/particle/Particle
	at se.Matryoshika.Underworld.Underworld.<init>(Underworld.java:61)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at net.minecraftforge.fml.common.ILanguageAdapter$JavaAdapter.getNewInstance(ILanguageAdapter.java:193)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:549)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.particle.Particle
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 35 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 37 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2390125320 bytes (2279 MB) / 3111124992 bytes (2967 MB) up to 3111124992 bytes (2967 MB)
	JVM Flags: 6 total; -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -Xmx3096M -Xms3096M -XX:PermSize=256m -XX:MaxPermSize=512m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2202 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (custom.jar) 
	UC	Forge{12.18.3.2202} [Minecraft Forge] (custom.jar) 
	UC	ezwastelands{1.10.2-1.0} [EzWastelands] (ezwastelands-1.10.2-1.0.jar) 
	UC	justenoughdimensions{1.2.0} [Just Enough Dimensions] (justenoughdimensions-1.10.2-1.2.0.jar) 
	UE	underworld{0.1.12} [Underworld] (underworld-1.10.2-0.2.12a.jar) 
	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Matryoshika** [comment]
For goodness sake =_=
Thought I fixed this potential issue in 0.2.12a, by moving the client-side code away from common, but seems I forgot to remove the old imports. (Java loads everything that is mentioned, and client-side only code (which, of course, doesn't exist on a server) was mentioned, but never used, because since 12a, it points to the client-proxy that deals with client-side only code. But it was mentioned. But doesn't exist. But was mentioned. <- That's Java's take on this issue)

Issue should be fixed.
Please try version **0.2.12b** which will be found here: https://minecraft.curseforge.com/projects/underworld/files/2370954
Just uploaded it, so it can take some time before it is available, as it needs to be verified first.
Please report whether or not 12b works for you :)

Good news :)
Will likely throw in more decorative stuff in Underworld soon, and I am working on porting structural worldgen (villages, temples etc) to a "quantum collection" where instead of actually placing the structures down, each block is added to a 3d list, as if they were placed, and then, once that is done, Underworld will have access to real structures, that I can actually fricking move and edit to fit in =_= I still fear for the Mojang dev that made the structure code. If I meet him, he will get slapped. Minimum.

**Comment by leezallen** [comment]
Brilliant, I will keep an eye out for it and let you know how it goes!

Good news about the structure generation! I remember trying to wrap my head around that a year or so ago while working on a project. In the end I gave up so happy that you have managed to figure it out! Out of curiosity are you planning any more custom structures at all?

**Comment by leezallen** [comment]
Thank you! 👍 

Can happily confirm that it all works quite happily with Forge server now! However I am getting a weird problem when I try to use SpongeForge (see here http://pastebin.com/gXp2iahE).

Completely understand if you want to claim that it is not really a priority for you at the moment... Just lots of server owners are turning to Sponge for the plugin integration. 

Just in case you do have a look the Pastebin above is the crash report... the log simply shows.

[20:32:14] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException
        at net.minecraft.world.WorldServerMulti.<init>(WorldServerMulti.java:18) ~[lo.class:?]
        at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:793) ~[WorldManager.class:1.10.2-2202-5.1.0-BETA-2053]
        at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:759) ~[WorldManager.class:1.10.2-2202-5.1.0-BETA-2053]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:330) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266) ~[ld.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]

Don't seem to get this issue with mods like ezWasteland (which I was going to partner your mod with in the new pack! Sort of like an apocalyptic overworld!)

**Comment by Matryoshika** [comment]
Sadly, your crash issue is not related to Underworld :(
Cannot help you there much.
I thought I recognized the crash-report, and a friend had the exact same issue on a pack without Underworld
Here's his [crashlog](http://pastebin.com/F3vXS245), which is really similar to yours, only with more mods in the pack.

I recommend that you try and contact sponge, and post an issue-report. I believe this issue is quite new, as I haven't had any issues with sponge myself (I'm an admin in a MC community during my free time xD )

Oh, and yes, I will likely be adding more structures, and will try and incorporate retro-gen features, so that map-resets will not be necessary.

**Comment by leezallen** [comment]
No problem! I really appreciate all the work you have put into the mod so you will have no complaints from me! (I am not one of those "the issue is yours. Fix it now" type people!!! I hate those people; it's why I walked away from mod/plugin development a couple of years ago!)

 I also think that the issue is due the to a recent Sponge API change too so if you don't mind I will do a little investigation myself, take a look at the code on both sides and see if I can figure it out why it is happening now. If I find anything I will PM you and let you know, maybe it will help out your friend too!

Again, thanks for all the work and the quick responses!
