### ISSUE TITLE
Conflict with Roots?

### ISSUE THREAD

**Issue by hairlessOrphan** [Matryoshika/Underworld#17]
Stack trace below, pulled from logs:

[14:52:58] [Server thread/INFO] [STDERR/]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:121]: java.lang.NoSuchMethodException: elucent.roots.entity.EntityAccelerator.<init>(net.minecraft.world.World)
[14:52:58] [Server thread/INFO] [STDERR/]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:121]: 	at java.lang.Class.getConstructor0(Class.java:3074)
[14:52:58] [Server thread/INFO] [STDERR/]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:121]: 	at java.lang.Class.getConstructor(Class.java:1817)
[14:52:58] [Server thread/INFO] [STDERR/]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:121]: 	at se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner.doSpawn(TileInvisMobSpawner.java:101)
[14:52:58] [Server thread/INFO] [STDERR/]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:121]: 	at se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner.func_73660_a(TileInvisMobSpawner.java:65)
[14:52:58] [Server thread/INFO] [STDERR/]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:121]: 	at net.minecraft.world.World.func_72939_s(World.java:1804)
[14:52:58] [Server thread/INFO] [STDERR/]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:121]: 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
[14:52:58] [Server thread/INFO] [STDERR/]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:121]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
[14:52:58] [Server thread/INFO] [STDERR/]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:121]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
[14:52:58] [Server thread/INFO] [STDERR/]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:121]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
[14:52:58] [Server thread/INFO] [STDERR/]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:121]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
[14:52:58] [Server thread/INFO] [STDERR/]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:121]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by Matryoshika** [comment]
Sorry for the long wait, been busy IRL >_>

Gaaaah
I swear that I've tried to fix this error so many times that I'm just gonna give up on having any way of stopping spam to console, from the catch block.

Gonna try a final thing, and block the MobSpawn mechanic from trying to spawn any Roots mobs, as I've just recently actually was able to play some Minecraft for once, and noticed that all the mobs from this mod are spawned by custom rituals, so they shouldn't be spawned automatically to begin with.

If that doesn't work, I'm likely just going to say "F--k it" and ignore any and all catched issues (won't get printed to console, but could hide further issues)

**Comment by Matryoshika** [comment]
This is just getting ridiculous =_= I swear I didn't mean to take this long.
Issue _**should**_ be fixed now. If it isn't I give up on.

Relevant code: https://github.com/Matryoshika/Underworld/commit/885d1207e0e62ddeb7dec8964b7b8609c0e8721b
